server:
  port: 10101

spring:
  application:
    name: mars-service-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    # 使用 Nacos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        - id: USER
          uri: lb://demo-service-user-consumer
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: SSO
          uri: lb://demo-service-sso
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
      # routes:
      #       - id: before_route
      #         uri: http://www.baidu.com
      #         predicates:
      #           - Path=/baidu
      # 此时当我们访问路径中包含/baidu的，gateway将会帮我们转发至百度页面
         
logging:
  level:
    com.wcmei.demo.service.gateway: debug
    com.alibaba.nacos.client.naming: error